### PR TITLE
Remove leftover Python 2 references

### PR DESCRIPTION
**Pull request by timlehr**
**Summarize your change.**

Removing some leftover Python 2 references in `setup.py`

### CODE REVIEW

**Review by apetrynet — COMMENTED** [review]
LGTM. 
However, I wonder if there are any more recent Python 3 versions to add?

**Comment by timlehr** [comment]
@apetrynet Not sure about the new Python versions. Which one do we support officially?

**Comment by apetrynet** [comment]
I don't know ATM. 
But adding the ones run in the ci should suffice. At least it's 1 to 1

**Comment by timlehr** [comment]
I think those are all present already.

**Comment by apetrynet** [comment]
Ah, sorry I was unclear. I meant in the versions listed in setup.py

**Comment by timlehr** [comment]
3.7 - 3.10 are already listed:
https://github.com/OpenTimelineIO/otio-aaf-adapter/pull/19/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R54-R58

**Comment by apetrynet** [comment]
Sorry, @timlehr
I should have expanded the diff 🤦‍♂️

**Review by apetrynet — APPROVED** [review]
Sorry about the delay. Looks good!
Thanks @timlehr !

**Pull request merged**
